import packageJson from './package.json' with { type: 'json' };

export default defineNuxtConfig({
  ...(process.env.PRINT_COST_BUILD_DIR ? { buildDir: process.env.PRINT_COST_BUILD_DIR } : {}),
  compatibilityDate: '2026-09-01',
  ssr: false,
  modules: [
    '@nuxt/ui',
    '@nuxtjs/i18n',
    '@querry-kit/nuxt-ui',
    '@pinia/nuxt',
    '@nuxt/eslint',
    '@vite-pwa/nuxt',
  ],
  css: ['~/assets/css/main.css'],
  devtools: { enabled: true },
  nitro: {
    preset: 'node-server',
    externals: { external: ['better-sqlite3'] },
    experimental: { openAPI: true },
    openAPI: {
      production: 'runtime',
      route: '/api/openapi.json',
      meta: {
        title: 'ezPrint API',
        description:
          'HTTP API for ezPrint. Sign in through /api/auth/login; the resulting print-cost-session cookie authenticates subsequent requests.',
        version: packageJson.version,
      },
      ui: {
        scalar: {
          route: '/api-reference',
          theme: 'saturn',
          agent: { disabled: true },
          mcp: { disabled: true },
          hideClientButton: true,
          telemetry: false,
          persistAuth: true,
          expandAllResponses: true,
          showDeveloperTools: 'never',
          defaultHttpClient: { targetKey: 'node', clientKey: 'axios' },
          pageTitle: 'ezPrint API',
          tagsSorter: 'alpha',
        },
        swagger: false,
      },
    },
  },
  runtimeConfig: {
    sessionTtlHours: 168,
    backupMaxBytes: 1024 * 1024 * 1024,
    public: { siteUrl: 'http://localhost:3000', appVersion: packageJson.version },
  },
  i18n: {
    langDir: '../app/i18n/locales',
    defaultLocale: process.env.DOCS_SCREENSHOTS === 'true' ? 'en-US' : 'de-DE',
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
    locales: [
      { code: 'de-DE', name: 'Deutsch', file: 'de-DE.json' },
      { code: 'en-US', name: 'English', file: 'en-US.json' },
    ],
  },
  colorMode: {
    preference: 'system',
    fallback: 'light',
    storageKey: 'print-cost-color-mode',
  },
  icon: {
    provider: 'none',
    clientBundle: {
      scan: true,
      icons: [
        'tabler:adjustments',
        'tabler:arrows-sort',
        'tabler:cancel',
        'tabler:eye',
        'tabler:eye-off',
        'tabler:filter',
        'tabler:filter-2',
        'tabler:grip-vertical',
        'tabler:layers-intersect-2',
        'tabler:layers-union',
        'tabler:pin',
        'tabler:pinned-off',
        'tabler:plus',
        'tabler:search',
        'tabler:sort-ascending',
        'tabler:sort-descending',
        'tabler:x',
      ],
    },
  },
  pwa: {
    registerType: 'prompt',
    client: { installPrompt: 'ezprint:pwa-install-dismissed' },
    manifest: {
      id: '/',
      name: 'ezPrint',
      short_name: 'ezPrint',
      description: 'Self-hosted 3D-print cost calculation.',
      start_url: '/',
      scope: '/',
      theme_color: '#1d4ed8',
      background_color: '#ffffff',
      display: 'standalone',
      icons: [
        { src: '/pwa-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        { src: '/pwa-maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    workbox: {
      globPatterns: ['**/*.{js,css,html,png,svg,woff2,json}'],
      globIgnores: ['**/sw.js', '**/workbox-*.js', 'manifest.webmanifest'],
      additionalManifestEntries: [{ url: '/', revision: packageJson.version }],
      navigateFallback: '/',
      navigateFallbackDenylist: [/^\/api(?:\/|$)/],
      cleanupOutdatedCaches: true,
    },
  },
  typescript: { strict: true, typeCheck: true },
});
